### ISSUE TITLE
Mobile first for 'news.html' and 'campus.html'

### ISSUE THREAD

**Issue by Clamvi** [Seytek/project_czu#2]
remake it so that the design was initially for mobile, and then through the 'media queries' make it for large screens.

p.s. i guess it will be easier to track the process here. 
5 min tutorial for 'github issues': [https://www.youtube.com/watch?v=TKJ4RdhyB5Y]

**Comment by sch3fr** [comment]
slow day at work, they block commiting to Github here but that won't stop me from making progress. So far:
### campus.html
- [x] mobile first container
- [x] mobile first search
- [x] mobile first section title
- [x] mobile first map section
- [x] mobile first points section

### news.html
- [x] mobile first container
- [x] mobile first search
- [x] mobile first menu
- [x] mobile first intro
- [x] mobile first section title

I'll commit the changes once I get back home

**Comment by Clamvi** [comment]
campus works good, great job!
I understood correctly that "news.html - mobile first" will be commited later?

**Comment by sch3fr** [comment]
I changed the news media querries to work mobile first, however now that I'm looking at it it does not seem to work very well. I'll look into it.

Edit: As far as I can tell the header is broken and the events section didn't scale at all. The events should be fixed now. I'm working on the header right now. Is there anything else I'm missing?

**Comment by Clamvi** [comment]
Thanks, no only header
