### ISSUE TITLE
requirements

### ISSUE THREAD

**Issue by Clamvi** [Seytek/project_czu#7]
Please look at the requirements for the project in case I missed something.
- [x] It says that we need to add contacts, make an additional contacts page, you can add content at your discretion. 
**`Franta`**, can you please make it, for example, throw a map there, which is located on the page campus.html and remove it from campus.html. And add random numbers and addresses.
- [x] **`Artur`**, I'll ask you to make the list of employees. It can can be added to the page education.html or faculties.html . It's up to you
- [x] I've added a page for searching

![Screenshot_1](https://user-images.githubusercontent.com/24972438/205148060-ffa9460a-b721
![Screenshot_2](https://user-images.githubusercontent.com/24972438/205148074-b548c77f-14f9-48dc-b660-d4f206c0a878.png)
-4631-b352-56f4a9062c52.png)

**Comment by sch3fr** [comment]
Sure, I'll make contacts page. I'm not sure about moving the map though. 
I'll play around with some ideas and commit it before the end of this week

**Comment by Clamvi** [comment]
Am I the only one who remembers that at the beginning of the semester 8 html pages were specified in the requirements?

**Comment by sch3fr** [comment]
yea I think I read somewhere that we should have 8 html files, but I can't find it now.

btw where was the link to departments.html supposed to be? I don't think we have it yet

**Comment by Clamvi** [comment]
Well initially pages event.html , department.html  should have been, but now the requirements do not specify about 8 pages. Do we need it? At least I thought not to add event.html because it wasn't completely finished by me.
access to department.html had to go through education.html.

**Comment by sch3fr** [comment]
fellas I'd like to remind you that the project deadline is this Sunday (11.12.22) so if there is any more work left we should do it ASAP so we can upload it

as for the requirements, last week I changed the tags on news.html so we have enough articles. Also there are grid elements in departments.html that span across several grid cells so we're good on that one. And I used aside on the departments page :)

should I add something to the contacts page?

**Comment by Clamvi** [comment]
no, just change the names :D, thanks

I'll try to finish by 10(pm) o'clock tonight. Therefore, be online after 10 o'clock to watch the final version. After that, I will upload the project to the site from the requirements.

The only thing is, I don't really know if we need to add figure, figcaption tags anywhere. 
**`Franta`**, can you add WCAG 2.1 please. I will also make it. As I know there should be some descriptions in alt atributs, labels and correct semantics

**Comment by sch3fr** [comment]
I don't think we'll need any figures. Though I started filling the alt attributes to images and other stuff

EDIT: On further inspection alt attribute is not suitable for anything other that images, so I guess we shouldn't add that to other things

**Comment by Clamvi** [comment]
Sorry guys, i dont have time today, tomorrow maybe will add something more. But I think its already okay, what do you think?

https://ete30e.pef.czu.cz/zs2223/036
its our project

**Comment by sch3fr** [comment]
51/60 points good job guys!
